api:
  id: "18146349"
# process API authentication details
client:
  id: ''
  secret: ''
https:
  private:
    port: "8092"
to:
  Address: "lchalla.cw@huronconsultinggroup.com,lchalla.cw@hcg.com,t-9chall@uchicago.edu,sai.krishna.cw@huronconsultinggroup.com"
cron:
  expression:   '0 0 9 * * ?'
retry:
 count: '3'
 interval: '30000'
categories:
  coa:  "Entity,Organization" #"Entity,Organization,Account,Fund,Purpose,Program,Activity,Site,Affiliate,Future"
  poetaf: "Project,Task,Exp_Org,Exp_Type,Funding,Award"
  
erp:
  ws:
    wsdl: 'https://fa-eusf-test-saasfaprod1.fa.ocs.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?wsdl'
    service: 'ExternalReportWSSService'
    port: 'ExternalReportWSSService'
    address: 'https://fa-eusf-test-saasfaprod1.fa.ocs.oraclecloud.com:443/xmlpserver/services/ExternalReportWSSService'
    username: 'integration_user'

sftp:
  directory:
   coa: "/opt/orafst/COA/"
   poetaf: "/opt/orafst/POETAF/"
  host: "205.208.116.22"
  port: "22"
  username: "orafstintdev"
  password: "![n+o5hm1QzxjjsaEhKsKYsZCvSyvAqPngIPoAODFKDBg=]"
  
smtp :
  uChicagoHost: "smtp.uchicago.edu"
  uChicagoPort: "25"
  fromAddress: "grif-feeds-request@lists.uchicago.edu"